CREATE TABLE CUSTOMER (
  C_CUSTKEY BIGINT NOT NULL,
  C_NAME VARCHAR(25),
  C_ADDRESS VARCHAR(40),
  C_NATIONKEY BIGINT NOT NULL,
  C_PHONE CHAR(15),
  C_ACCTBAL DECIMAL,
  C_MKTSEGMENT CHAR(10),
  C_COMMENT VARCHAR(117)
);
CREATE TABLE NATION (
  N_NATIONKEY BIGINT NOT NULL,
  N_NAME CHAR(25),
  N_REGIONKEY BIGINT NOT NULL,
  N_COMMENT VARCHAR(152)
);
CREATE TABLE REGION (
  R_REGIONKEY BIGINT NOT NULL,
  R_NAME CHAR(25),
  R_COMMENT VARCHAR(152)
);
