CREATE TABLE CUSTOMER (
  C_CUSTKEY BIGINT NOT NULL,
  C_NAME VARCHAR(25),
  C_ADDRESS VARCHAR(40),
  C_NATIONKEY BIGINT NOT NULL,
  C_PHONE CHAR(15),
  C_ACCTBAL DECIMAL,
  C_MKTSEGMENT CHAR(10),
  C_COMMENT VARCHAR(117)
);