CREATE TABLE PART (
  P_PARTKEY BIGINT NOT NULL,
  P_NAME VARCHAR(55),
  P_MFGR CHAR(25),
  P_BRAND CHAR(10),
  P_TYPE VARCHAR(25),
  P_SIZE INTEGER,
  P_CONTAINER CHAR(10),
  P_RETAILPRICE DECIMAL,
  P_COMMENT VARCHAR(23)
);
CREATE TABLE SUPPLIER (
  S_SUPPKEY BIGINT NOT NULL,
  S_NAME CHAR(25),
  S_ADDRESS VARCHAR(40),
  S_NATIONKEY BIGINT NOT NULL,
  S_PHONE CHAR(15),
  S_ACCTBAL DECIMAL,
  S_COMMENT VARCHAR(101)
);
CREATE TABLE PARTSUPP (
  PS_PARTKEY BIGINT NOT NULL,
  PS_SUPPKEY BIGINT NOT NULL,
  PS_AVAILQTY INTEGER,
  PS_SUPPLYCOST DECIMAL,
  PS_COMMENT VARCHAR(199)
);